### ISSUE TITLE
Gearswap - pet_status_change is occasionally not called

### ISSUE THREAD

**Issue by Sygloon** [Byrth/Lua-Byrth#367]
User function pet_status_change(new,old) is not called.
I define this function to pup.lua.
In a state in which the automaton active and not invoked even after sitting and standing

**Comment by Byrth** [comment]
Okay, thank you. I will look into it tonight.

**Comment by Byrth** [comment]
Were you using the Sharpshot (ranged) Automaton? It appears that this automaton does not engage unless the first shot fails to kill the target.

**Comment by Byrth** [comment]
I believe I may have solved this problem. Now it does trigger pet status change events for /heal and /sit. I was unable to find any other problems related to battle.

Was this the problem that you had?

**Comment by Sygloon** [comment]
At the scene of me and automaton are attacking a different target,
Automaton's target killed by area damage(i.e.Spinning Attack)
Automaton is idled, then i expect trigger pet_status_change()
i want to do JA Deploy in pet_status_change(), but called pet_status_change()

**Comment by Byrth** [comment]
Okay, I understand the problem now. I'll check it out when I get a chance.

**Comment by Byrth** [comment]
I think I finally figured out what causes this and fixed it. It should be live in v0.913
