### ISSUE TITLE
Weird battlemod issue

### ISSUE THREAD

**Issue by KenshiDRK** [Byrth/Lua-Byrth#368]
Im having a weird issue with battlemod, sometimes it will stop parsing the battle messages to the chat log for unknown reasons. After unloading the normal battle messages start to appearing. I haven't seen a similar issue posted so not sure if its something in my end.

**Comment by Byrth** [comment]
It is likely a problem in hook with add_to_chat. I have never seen it personally.

I will report this on the windower tracker when I get home, but because it is not a battlemod issue I will close it here.
