### ISSUE TITLE
gearswap/refresh.lua:529: "id" is not defined for numbers

### ISSUE THREAD

**Issue by Dragomair** [Byrth/Lua-Byrth#371]

**Comment by Byrth** [comment]
This doesn't happen for me. You probably have mismatched versions of the addon library.

* Go to this page: https://github.com/Windower/Lua
* Click the "Download zip" link on the right.
* Extract it 
* Copy the gearswap and libs folder to your addons directory.

Reload gearswap in game (//lua r gearswap).

This will probably fix your problem.
