### ISSUE TITLE
im not sure if you want this or not(an updated nin tool map for gearswap)

### ISSUE THREAD

**Issue by smd111** [Byrth/Lua-Byrth#375]
http://pastebin.com/SsGfG3Qj

to get the tools you just need
nin_tool_map[spell.english].tool[language]--for normal tool
nin_tool_map[spell.english].tool_bag[language]--for normal tool bag
nin_tool_map[spell.english].universal_tool[language]--for universal tool
nin_tool_map[spell.english].universal_tool_bag[language]--for universal tool bag

**Comment by smd111** [comment]
i also have one for cor cards

**Comment by Byrth** [comment]
You could make this into a library for gearswap and release it if you want, but I don't have a use for the COR cards and I already made one for Ninjutsu (Lines 218~312 in statics.lua).

**Comment by smd111** [comment]
im not sure how it should be made in to a library for gearswap

**Comment by Byrth** [comment]
Put all the hardcoded tables like that into one file and name it smd_resources.lua or something. Then do a pull request that would put it in gearswap/libs.
Then people can do include('smd_resources') and it'll pull your tables in.

**Comment by Byrth** [comment]
Going to close this because it's better as a library than a part of gearswap that would be included all the time.
