### ISSUE TITLE
Battlemod Runtime error

### ISSUE THREAD

**Issue by Juztinius** [Byrth/Lua-Byrth#379]
When ever I log in or load battlemod i get an error "Battlemod: Lua runtime error: Libs/files.lua : 187 attempt to index local 'fh' (a nil value). If i ignore the issue it results in a battlemod crach or battlemod runs but ever other line is an error wihting chat  "battlemod error, missing filter:nil P0" and "battlemod error, missing filter: nil mob"

**Comment by Byrth** [comment]
It sounds like your libraries may be out of date. Try downloading new ones from windower/Lua github repository and replacing the ones yo have. On phone so I cannot link. Look for the Zip icon on the right side of the page (I think).

**Comment by Juztinius** [comment]
Gave that a try and still getting the same runtime error

**Comment by Juztinius** [comment]
Ironically it seems i only get this error/crash while on dancer. as soon as i zone or change to dnc i recieve the error. I can smoothly use battelmod on my RUN

**Comment by Byrth** [comment]
Try loading a blank document instead. I suspect the problem may be in your file?

**Comment by Byrth** [comment]
Given no response in months, I assume the problem resolved itself.
