### ISSUE TITLE
gearswap nil value error

### ISSUE THREAD

**Issue by theblackdeath** [Byrth/Lua-Byrth#381]
lua runtime error: gearswap/gearswap.lua:384: attempt to index field '?' (a nil value)

gearswap: lua runtime error: libs/texts.lua:579: attempt to compare nil with number

**Comment by theblackdeath** [comment]
Gearswap: lua runtime wrror: Gearswap/triggers.lua:285: attempt to index local 'tempplay' (a nil value}

**Comment by z16** [comment]
It would be very helpful if you mentioned what you did to get that error and what your GS file looks like.

**Comment by theblackdeath** [comment]
the job file or the gearswap.lua file

and as for what i did it was kneeling or just standing there

**Comment by z16** [comment]
The job file.

**Comment by theblackdeath** [comment]
gearswap.lu line 384  if not items[bag][slot] then items[bag][slot] = make_empty_item_table(slot) end
        items[bag][slot].id = data:unpack('H',0x0D)
        items[bag][slot].count = data:unpack('I',5)
        items[bag][slot].bazaar = data:unpack('I',9)
        items[bag][slot].status = data:byte(0x11)
        items[bag][slot].extdata = data:sub(0x12,0x29)

libs/texts.lua line  579   return (pos_x <= x and x <= pos_x + off_x     in the function texts.hover(t, x, y)


triggers lua line 289  is  else
                prefix = 'pet_'

of the 
if arr.actor_id ~= tempplay.id then
        if tempplay.pet_index then
            if arr.actor_id ~= windower.ffxi.get_mob_by_index(tempplay.pet_index).id then
                return
            else
                prefix = 'pet_'
            end
        else
            return
        end
    end

**Comment by theblackdeath** [comment]
one sec ill github it

**Comment by theblackdeath** [comment]
https://gist.github.com/theblackdeath/de42d61c21d4b57f54f2

**Comment by theblackdeath** [comment]
the triggers error kicked off as thirdeye wore  and the libs one if i open my console and left click the mouse it adds the error at 579 to the log

**Comment by theblackdeath** [comment]
well i guess just clicking the left click does it

**Comment by theblackdeath** [comment]
if it helps you at all earlier cair asked me o type //eval print(windower.ffxi.get_player()) which came back nil

**Comment by Byrth** [comment]
Yeah, the fact that windower.ffxi.get_player() comes back nil indicates that LuaCore isn't loading your information for some reason. That'll break all kinds of stuff, including GearSwap. However, it's also out of the scope of my addon tracker. I'm going to close this because it looks like it's somehow a problem with LuaCore (this would be the first time anything like this has been reported as far as I know).

I opened an issue on the windower issue tracker for you that references this: https://github.com/Windower/Issues/issues/732
