### ISSUE TITLE
Organizer mixed results

### ISSUE THREAD

**Issue by jcv-** [Byrth/Lua-Byrth#384]
I can't seem to get organizer to work properly. 

On one character after running //gs org i get the message saying organizer is starting; however, it never seems to finish. It also causes other addons to stop functioning. For example, doing //lua list shows no addons loaded and the only way to resolve the issue is to close the FFXI process. (GS: http://pastebin.com/33pGucf7)

On another character I receive "Lua runtime error: libs/extdata.lua:1388: attempt to index field 'potency' (a nil value). (GS: http://pastebin.com/uQcrpt4m)

In both scenarios organizer seems to halt and not move any items.

I have tried deleting the folder and letting windower download organizer again, but run into the same results.

**Comment by Byrth** [comment]
Many organizer fixes were pushed out tonight. Please let me know if you still have issues. If you do, I'm going to need to know what augments are on your item that cause the extdata error.

**Comment by jcv-** [comment]
Hey Byrth, thanks for the update.

I actually found the item that was causing issues (http://www.ffxiah.com/screenshots/32743).

The only other issue that I have now is that organizer doesn't seem to be pulling items out of mog safe 2. However, I will test tomorrow with the new updates.

Thanks!

**Comment by Byrth** [comment]
Oh god, Evolith augments.

I believe my evolith augment mapping in extdata.lua is incomplete (because there are a ton of evolith augments). That said, I don't know why it doesn't work. I'll try to take a look at it tomorrow if the free login campaign is still running.

**Comment by jcv-** [comment]
Organizer seems to be grabbing my gear properly after the new update; however, I am still running into the following issue:

After running organizer, it looks as if something is happening to lua. I can't unload, load, reload addons. I can run //lua and get the help information and doing a //lua list shows no running addons. The only one for me to restore functionality is to kill the FFXI process (doing a /shutdown causes FFXI to hang). Also, this only appears to be happening on my alt character (dual boxing), the main character never seems to be affected.

**Comment by Byrth** [comment]
That indicates that organizer is deadlocking the addon thread, which shouldn't happen. Rooks or I will look at it later.

**Comment by hell514** [comment]
Having the exact same issue as JCV, on my main toon nothing is wrong I can enter console commands and organizer works fine. However, on my alt character organizer/gearswap/shortcuts appear to be affected. I have tried logging on my alt char only, but the issue is still there and when trying to shutdown (only on my alt) it just hangs.

**Comment by hell514** [comment]
Seems there was an update to the Add-ons via Windower, now the error message when trying to do //gs org is: Organizer: Cannot move item (********). It has already been annihilated, not sure why its doing that and it still only happens on the alt character, and freezes when trying to shutdown.

**Comment by hell514** [comment]
And on a second note it deleted items from my alt characters inventory ><

**Comment by Byrth** [comment]
Organizer can't drop items, if that's what you meant, because it doesn't send the packet for it. At the worst (and I've never seen this happen) it'll confuse your client into thinking the item isn't around and you'll have to zone to reset your client's inventory.

You guys are describing deadlocks in the addons thread. I know that Rooks is investigating this and I'll try and pop on IRC and help with it later.

**Comment by kelhor** [comment]
So, re: deletion. It's possible to put things in safe2 even if it's not unlocked. That's awful on SE's part, but that's the fix, is to unlock safe2. I'm going to patch this shortly.

**Comment by Byrth** [comment]
Given that this has been patched for a while, I'm going to close the thread.
