### ISSUE TITLE
organizer : Bug with last windower update

### ISSUE THREAD

**Issue by mijean** [Byrth/Lua-Byrth#385]
got an error on organizer load :
lua runtime error blablabla organizer.lua:140 bad arguments #1 to pairs, table expected got nil

when i try to //gs org it doesn't start and get another errror
lua runtime error blablabla organizer.lua:418 attempted to index field 'default file' (a nil value)

**Comment by kelhor** [comment]
Can I see your config? This looks like a config issue.

**Comment by mijean** [comment]
you mean the settings.xml of organizer?  it's actually empty :
<?xml version="1.1" ?>
<settings>
    <global>

    </global>
</settings>

if you want another config, i'll be happy to copy paste it here, just don't know which one lol

**Comment by kelhor** [comment]
How did you get a file with no settings? Just delete that whole file and reload organizer, and you should get a new one with fresh defaults.

**Comment by mijean** [comment]
yup, unloaded addon, deleted settings, reloaded, had the notice that a new settings was created, and now i have a real settings with many parameters.

reloaded the addon, no error message this time, gonna check as soon as i head to my mog house for any other errors, but it should be fine now. thanks for the hint ^^
