### ISSUE TITLE
Gearswap: error when using macros while sitting on a chair

### ISSUE THREAD

**Issue by Grouf** [Byrth/Lua-Byrth#387]
While sitting on chair 2 and using a macro to cast a spell using either <me> or <stal> I got the following error:  GearSwap: Lua runtime error: GearSwap/refresh.lua:216: attempt to index field '?' (a nil value)

Not a big deal since you can't do anything while sitting but I thought you should know in case this leads to a bigger issue. 

Thanks for all the work on this!

**Comment by Byrth** [comment]
This is caused by having a character status that's not included in res.statuses.

**Comment by Byrth** [comment]
Okay, I just added this status to ResourceExtractor (status 63) and it will no longer cause errors after the next resources update.
