### ISSUE TITLE
Sapience Orb not being detected in GS.

### ISSUE THREAD

**Issue by Hiep1882** [Byrth/Lua-Byrth#388]
Here is my precast set,
	sets.precast.FC = {main="Tupsimati",
                          sub="Willpower Grip",
                          ammo="Incantor Stone",
                          head="Nahtirah Hat",
                          body="Anhur Robe",
                          hands="Gende. Gages +1",
                          legs="Psycloth Lappas",
                          feet="Pedagogy Loafers +1",
                          neck="Orunmila's Torque",
                          waist="Witful Belt",
                          right_ear="Loquac. Earring",
                          left_ear="Etiolation Earring",
                          right_ring="Prolix Ring",
                          left_ring="Weather. Ring",
                          back="Swith Cape +1"}
For some reason, the orb does not swap in. I've tried //gs export, triple checked spelling and commas. Also tried replacing in Incantor Stone in its place and it worked fine, but when I reversed it and placed back in Sapience Orb, it's still not swapping in.

**Comment by Byrth** [comment]
This is a resources issue. I reported it to Arcon on IRC and opened an issue here:
https://github.com/Windower/ResourceExtractor/issues/40

**Comment by Hiep1882** [comment]
Thank you Byrth!
