### ISSUE TITLE
Runtime Error: Refresh.lua

### ISSUE THREAD

**Issue by vm0d** [Byrth/Lua-Byrth#391]
While sitting in a chair, I am getting this error:

Gearswap: Lua runtime error: gearswap/refresh.lua:216: attempt to index field '?' (a nil value)

**Comment by Byrth** [comment]
Do you have one of the new chairs?

If not (and maybe even if you do), that probably indicates that your resources are old, I think. New resources have a sitting status for chairs.

**Comment by vm0d** [comment]
it happened in both the chocobo chair and the bastok chair.

i've relogged today and it is still giving me the error.

**Comment by Byrth** [comment]
Hmm.... perhaps they're different chair statuses. I'll check it out tonight. How do you get those chairs? I think I have one chair from CP and that's it.

**Comment by vm0d** [comment]
sorry for delayed response ><

chairs:
bastok chair - change allegiance to bastok and 10k cp from gate guard
sandy chair - change allegiance to sandy and 10k cp from gate guard
windy chair - change allegiance to windy and 10k cp from gate guard
jeuno chair - any city allegiance, 20k cp from gate guard
shadow throne - 2m cruor from abyssea cruor prospectors or bonecraft recipe
chocobo chair - 500 chocobucks or 15k mummer's medals from masad
somethingsomething crate - 50k allied notes from sigil npc
ephremadian chair/something - 50k imperial standing from signet npc

also, i've only been on rng, so it might have something to do with my
rng.lua? not sure, but i have attached it jic.

**Comment by Byrth** [comment]
Okay, I submitted the required change to ResourceExtractor. It should be fixed next time the resources go out.

**Comment by vm0d** [comment]
thank you^^
