### ISSUE TITLE
party.count broken

### ISSUE THREAD

**Issue by intrloper** [Byrth/Lua-Byrth#396]
After the recent updates it seems party.count isnt working.
Added: print(party.count)
to test the return and it returned 0 in all situations.
Tried with a trust out, in a party with another player, and finally is same party with said player with him as leader.
All returned a 0.

Code in question is this:(elseif is just the section i am copying)

    elseif player.status == 'Idle' then
        equip(sets.idle, sets.misc.DT[dt_mode], sets.misc.Movement)
        if dt_mode == 'None' then
            print(party.count)
            if party.count > 1 then
                equip(sets.idle.SphereRefresh)
            end
            if player.mpp < 50 then
                equip(sets.idle.under_50mpp)
            end
            if check_buffs('Reive Mark') then
                equip(sets.misc.Reive)
            end
        end
    end

Thank you for the time, will be working all week but if I can help in anyway I will.

**Comment by Byrth** [comment]
Okay, finally figured this one out. Going to push a fix to -dev later today.
