### ISSUE TITLE
GearSwap/refresh.lua:234: runtime error

### ISSUE THREAD

**Issue by ragnark78** [Byrth/Lua-Byrth#398]
i'm getting the following error ...

Gearswap: Lua runtime error: GearSwap/refresh.lua:234: attempt to index field '?' (a nil value)

**Comment by Byrth** [comment]
```player.race = res.races[player.race][language]```

What race are you / were you wearing a costume / etc.?

**Comment by Byrth** [comment]
Thinking about it a bit more, this might also be caused by out of date resources. Here is a link to the current windower/res/races.lua : https://www.dropbox.com/s/02ov80fc6ljim15/races.lua?dl=0

**Comment by ragnark78** [comment]
it was an issue with blinkmenot ... just came back to the game after a 9 month break so i was behind on reading up on the current glitches.


________________________________

**Comment by Byrth** [comment]
Good to know. Going to close this issue then.
