### ISSUE TITLE
Gearswap - pet_midcast too slow for automaton WS

### ISSUE THREAD

**Issue by benjaminGitHub** [Byrth/Lua-Byrth#404]
Based on tests using Cannibal Blade on Blanced Mandragora w/ tp bonus gear. Cannibal Blade is a very consistent ws in terms of dmg that varies with TP.

Using the following code:

    function pet_midcast(spell)
        windower.send_command('input /echo spell '..spell.name..'. 1')
        equip(sets.midcast.Pet.WeaponSkill)
    end

and

    sets.midcast.Pet.WeaponSkill = {head="Karagoz Capello +1", hands="Karagoz Guanti", legs="Karagoz Pantaloni +1", waist="Incarnation Sash", back="Dispersal mantle", body="Pitre Tobe +1", ring1="Overbearing ring", ring2="Thurandaut Ring", ear1="Burana Earring"}

gs showswaps shows that the gear is changing during midcast, but the damage is ~900.
Equipping sets.midcast.Pet.WeaponSkill manually and turning off gearswap consistently puts the WS damage over 1200.

I'm guessing that the system is working as written, but it just can't detect the pet WS fast enough to equip the gear in time to increase damage. Not sure if this would be considered a real bug or not.

I did some research on this issue, and found out that someone else had this issue: http://www.ffxiah.com/forum/topic/41580/gearswap-support-thread/64/
but no resolution.

Forgive me for any mistakes or misunderstandings I have. I am new to gearswap.

**Comment by Byrth** [comment]
Yeah, it's not actually an issue that I can do anything about. Automaton WSs (and all pet WSs) are initiated by the server, so there's nothing I can do to make a pet_precast function. Avatars and BST pets typically have a longer delay, so this solves the problem for them, but Automatons don't and also their WSs aren't always associated with a job ability usage so you can't do something like use aftercast for a Sic command to equip your pet damage gear.

Sorry, that's just how it has to be.

**Comment by benjaminGitHub** [comment]
I was afraid of that. Thank you for explaining it to me.
