### ISSUE TITLE
GearSwap: Spells/JAs that the character does not know does not call filtered_action()

### ISSUE THREAD

**Issue by flippant** [Byrth/Lua-Byrth#408]
In helper_functions.lua, filtered_pretarget function: "return false" for the condition on 618 fixes the issue. However, I think we talked about this before, and I don't remember your response and if there was a reason to not have it call filtered_action.

Thanks.

**Comment by Byrth** [comment]
After looking at it and thinking about it, I have to conclude that the "return false" was just accidentally deleted at some point. Added it back in to v0.913
