### ISSUE TITLE
GearSwap: Job Point Spells/Abilities for JP client throwing error

### ISSUE THREAD

**Issue by flippant** [Byrth/Lua-Byrth#409]
In helper_functions.lua, filter_pretarget function, player.main_job resolves to the Japanese job name in the Japanese client, so the table is not found. I changed it from

number_of_jps(player.job_points[__raw.lower(player.main_job)])

to

number_of_jps(player.job_points[__raw.lower(res.jobs[player.main_job_id].ens)])

in two places as a quick fix for my friend, but maybe there is something shorter.

Thanks.

**Comment by Byrth** [comment]
Thanks! Fixed in version 0.913
