### ISSUE TITLE
instaLS Issue

### ISSUE THREAD

**Issue by Hiep1882** [Byrth/Lua-Byrth#413]
For some reason, the Addon is not working for me since the most recent update.

**Comment by Byrth** [comment]
How does it not work?

**Comment by Hiep1882** [comment]
As in I still have to wait the 10-15 second delay before I can type a message in any of my linkshells after zoning. I double checked and the addon is loaded.

**Comment by Byrth** [comment]
Try reloading it after you login and then zone+test.

If that makes it work, the problem is one of your other addons and I'd need a list of them.

**Comment by Hiep1882** [comment]
Yes, reloading after I logged in and zone/testing seemed to make it work. My other addons are: battlemod, boxdestroyer, Chatlink, distance, enternity, eval, findALL, Gearswap, instaLS, linker, Logger, macrochanger, PetTP, pointwatch, respond, rolltracker, scoreboard, setbgm, shortcuts, silence, thtracker, TParty, translate, update, and zonetimer. Thanks so much for looking into this Byrth!

**Comment by Byrth** [comment]
Hmm... the only 3 addons that should be able to interfere with it (change outgoing text) are:
Gearswap
shortcuts
translate

I use all of those addons all the time. Did you alias something to the shortcut "l" or "l2" in shortcuts?

**Comment by Byrth** [comment]
I managed to replicate *an* InstaLS issue, but I don't know if it's this one. For some reason my chat came out in the /s channel just now when I said something after zoning.
