### ISSUE TITLE
Point Watch: Lua runtime error:

### ISSUE THREAD

**Issue by rebelrednk** [Byrth/Lua-Byrth#419]
when i try to load point watch i get this error message "Lua runtime error:  libs/config.lua:94: XML error: Malformatted XML headers."  how do i fix this so point watch will work again

**Comment by Byrth** [comment]
Probably has something to do with your pointwatch config xml file. Can you pastebin it for me please?

**Comment by Byrth** [comment]
Going to assume this was a problem with the xml file. Please reopen it if the issue persists and you can pastebin your xml.
