### ISSUE TITLE
GearSwap - '//gs o' caused organizer-lib.lua:147: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Isilrhofal** [Byrth/Lua-Byrth#424]
GearSwap: Lua runtime error: gearswap/flow.lua:102:
User Event Error: ...6)Windower4/addons/gearswap/libs/organizer-lib.lua:147: attempt to index field '?' (a nil value)

This happens when I try to get my gear for any job using '//gs o' .

**Comment by Byrth** [comment]
We probably just need a resources update and this problem will go away.

**Comment by Isilrhofal** [comment]
Ok, I will observe the behavior - thank's for the response.

**Comment by Byrth** [comment]
Is this fixed now?

**Comment by Isilrhofal** [comment]
Thank you,
Just tested it and it is working again.
