### ISSUE TITLE
Gearswap - Mog Wardrobe 3/4 Issue

### ISSUE THREAD

**Issue by OrphenPUP** [Byrth/Lua-Byrth#428]
Hello, Sorry to bother you as Im sure this is expected due to the update.  I have not seen it posted on any forums so wanted to add the following error I have been receiving.

With addition of Mog Wardrobe 3 & 4, once equipment is moved into wardrobe 3 or 4.  Start receiving following error:
> GearSwap:  Lua runtime error: GearSwap/Gearswap.lua:415: attempt to index field '?' (a nil value).

Observations:
Error seems to happen whenever changing zones.
Removing gear from Wardrobe will fix issue temporarily until used again.

**Comment by Byrth** [comment]
Thanks! I will address this but it is going to take me a week.

**Comment by z16** [comment]
We just merged a pull request that added wardrobe 3/4 functionality to GS. Can you see if it works for you now?

**Comment by Byrth** [comment]
My linkshell reports everything is working.
