### ISSUE TITLE
Gearswap - Reading Equipped Gear by Bag

### ISSUE THREAD

**Issue by flippant** [Byrth/Lua-Byrth#431]
Wasn't sure how to title this exactly.

I had been specifying multiple gear by bag so that I didn't have to update all my files every time I changed augments. Equipping it this way works directly, but the logic that determines if you are already wearing a certain piece of gear already, and therefore whether to switch to the new gear, isn't taking this into account like it does with augments. So, for example, I end up casting nukes in all my FC versions of Merlinic (bag="wardrobe") rather than MB versions (bag="inventory").

I've changed it now, so it's not a big deal to me, and I think most people just specify by augment, but thought I should bring it up.

**Comment by Byrth** [comment]
I believe that I fixed this on -dev just now.

Please open a new issue if you run into the problem again.
