### ISSUE TITLE
Shortcuts - Name that starts with scan crashing when you don't have a widescan target.

### ISSUE THREAD

**Issue by Selindrile** [Byrth/Lua-Byrth#438]
If you try to use shortcuts to cast a spell with the target name of "scan" without a widescan target, full Windower crash, uploading a crashdump.

https://www.dropbox.com/s/46c04v5iitn3c2z/pol.exe.5004.dmp?dl=0

Probably need to add a check to see if you have a widescan target, and have it default to checking player names when you have no widescan target. (My friend discovered the issue trying to cure someone whose name started with scan and was using /cure4 scan.)

**Comment by Byrth** [comment]
Good to know, likely a check that needs to be added in LuaCore or hook. I'll repost this issue on the windower tracker.

**Comment by Byrth** [comment]
Given that I opened this issue on the other tracker, I'm going to close it here.
