### ISSUE TITLE
Gearswap: Bard weapon and ranged issue post-update (2/25)

### ISSUE THREAD

**Issue by Hopefulki** [Byrth/Lua-Byrth#440]
My LUA is based off of Moten's BRD Lua (include heavy). Mine is modified for differing levels of debuffs and potency vs duration. After today's GS update, my Daur dummy songs don't work (as in it won't equip Daub), and Carn won't equip during midcast. This seems to only be affecting main/sub and ranged slots - the rest of my gear is equipping perfectly, including the dummy/fast cast. 

Thanks

**Comment by Hopefulki** [comment]
This was using the dev build, not stable. Stable is fine.

**Comment by Byrth** [comment]
How did this work out for you with 0.928?

**Comment by Hopefulki** [comment]
This appear to have been solved - thanks very much !

**Comment by Byrth** [comment]
No problem!
