### ISSUE TITLE
Windower crashing while idle

### ISSUE THREAD

**Issue by Tidis** [Byrth/Lua-Byrth#441]
Hello, I have been crashing a lot lately, I recently just logged in and left my character and it would still crash after a short time, I have included a crash dump.

https://www.dropbox.com/s/ks3894whc5b1hj7/pol.exe.2580.dmp?dl=0

**Comment by Byrth** [comment]
This may have been fixed by a hook update since then.

Please report general crashing things at http://github.com/Windower/Issues/issues/
