### ISSUE TITLE
Battlemod error, missing filter nil: p0

### ISSUE THREAD

**Issue by Pasimoso** [Byrth/Lua-Byrth#444]
Hi, I'm getting errors for battlemod after the July 5th, update. The error is just as the titles suggest. 

"Battlemod error, missing filter:nil p0" To be exact. 

Also in the command window, I'm getting this message:
"Battlemod: Lua runtime error: libs/config.lua94: XML error: Malformatted XML headers."

Any help please? 💯

**Comment by Pasimoso** [comment]
Problem solved.

**Comment by Gorns** [comment]
Hi Gents,

I got the same error messages, exactly same wording.
Could you tell me how you fixed it ?

Thanx

**Comment by Byrth** [comment]
It is probably caused by a corrupted xml file. You could try deleting your settings and letting them get regenerated by Battlemod. Going to close this
