### ISSUE TITLE
Gearswap-Thunderspark (avatar BP gear issues)

### ISSUE THREAD

**Issue by Frodnonnag** [Byrth/Lua-Byrth#445]
Avatar bloodpact midcast sets land in incorrect gear. This is most frequent/immediately noticeable  in higher lag situations using Thunderspark (cleaving mobs in swarms and alliance content).

it appears that the pact is landing in either precast gear (the -bp timer step), or the post cast idle sets.
[Frod_smn_txt.txt](https://github.com/Byrth/Lua-Byrth/files/1178533/Frod_smn_txt.txt)

**Comment by Byrth** [comment]
I think this is a problem basically with the way I named the Pet events. Pet Midcast is not really comparable to Player Midcast. See my response at the bottom of this thread for more information:
https://github.com/Windower/Lua/issues/1596
