### ISSUE TITLE
Gearswap error libs/socket

### ISSUE THREAD

**Issue by zaxtiss** [Byrth/Lua-Byrth#446]
Hello,

so I just got a new pc and I now have this issue with gearswap it say
"gearswap error libs/sockets line 42 failed to call global (newtry).
it wont even load any of my GS's or a blank GS file. any clue what I need to do?

**Comment by Byrth** [comment]
Has this problem gone away? I suspect the sockets library was updated and caused it, but was probably fixed by now.

**Comment by Byrth** [comment]
Assuming it is fixed.
