### ISSUE TITLE
pet animation not working

### ISSUE THREAD

**Issue by GTOutlaw** [Byrth/Lua-Byrth#452]
when I use my pet commands none of them show any animation

**Comment by Byrth** [comment]
This is related to an addon named pet_fix .

If you unload it ( //lua u pet_fix ), your pets should use TP moves again. At some point I think pets using TP moves was crashing people, so I made an addon for it.

**Comment by GTOutlaw** [comment]
I am using the pet_fix addon and my pet still makes no action when attacking or using weaponskills.
