### ISSUE TITLE
Exporting augmented gear pasting in BLU.lua not working

### ISSUE THREAD

**Issue by germthevicious11** [Byrth/Lua-Byrth#457]
Ive tried for hours many different things. i equipped the gear, export it, open the exported lua in notepad++, copied the item exactly and put it in the job.lua in this case BLU.lua for blue mage. it will not recognize my item. and when i try to force equip it it says "That set does not exist".

here is the exact command line looks exactly like all the other already entered items from Spicyryans blue.lua files.

HerculeanHelm.TA = { name = "Herculean Helm", augments = { 'Accuracy+30','"Triple Atk."+3','DEX+5', } }

**Comment by germthevicious11** [comment]
i even took his already registered item named and copied my items strings from the export to it just to test if it would work and it still wont

HerculeanHelm.Nuke = { name = "Herculean Helm", augments = { 'Accuracy+30','"Triple Atk."+3','DEX+5', } }

**Comment by Byrth** [comment]
This was almost certainly a user file problem and it is >1 year stale, so I am going to close it.
