### ISSUE TITLE
Gearswap - Ambuscade JSE Counter Augment

### ISSUE THREAD

**Issue by Radianze** [Byrth/Lua-Byrth#462]
The counter+ augment when using export does not come back correctly.
back={ name="Segomo's Mantle", augments={'STR+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','System: 1 ID: 640 Val: 3',}},

**Comment by Byrth** [comment]
Interesting. It should still work, but this means that Counter+10 or whatever it is would not work. I recommend reporting this on the main Windower Lua issue tracker as I haven't played FFXI in 2.5 years and am going to archive this repo.
