### ISSUE TITLE
Equip_Processing Error

### ISSUE THREAD

**Issue by deathfrombelow** [Byrth/Lua-Byrth#464]
Get the following errors after the April 2020 update:

GearSwap: Lua runtime error: GearSwap/equip_processing.lua:255: attempt to index field '?' (a nil value)
&
autocontrol: Lua runtime error: autocontrol/autocontrol.lua:85: attempt to call method 'category' (a nil value)

**Comment by Byrth** [comment]
Please report this on the windower-lua repo. This is basically closed.
